# Generated by Django 2.2.7 on 2019-11-25 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='image',
            new_name='isImage',
        ),
    ]
