# Generated by Django 2.2.7 on 2019-11-26 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20191125_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='imagePath',
            field=models.ImageField(default=0, upload_to='images/'),
            preserve_default=False,
        ),
    ]
