# Generated by Django 2.2.7 on 2019-11-26 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_message_imagepath'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='imagePath',
        ),
    ]
